---
title: Heatmap
author: "pz"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    highlight: tango
    df_print: paged
    toc: yes
    toc_float:
      collapsed: false
      smooth_scroll: true
    toc_depth: 3
    code_folding: hide
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE, result='hold',fig.width=8,tidy=TRUE, cache=FALSE)
knitr::opts_knit$set(progress=TRUE,verbose=TRUE)
```

```{r libraries, cache=FALSE}
library(data.table)
library(magrittr)
library(knitr)
library(ggplot2); theme_set(theme_bw(base_size = 16))
library(DESeq2)
library(ggsci)
library(dplyr)
library(pheatmap)
library(openxlsx)
library(kableExtra)
library(RColorBrewer)
```

```{r decoder}
decoderFile <- "decoder.txt"
decoder.data <- fread(decoderFile) %>% as.data.frame()
decoder.data$source <- factor(decoder.data$source)
decoder.data$condition <-factor(decoder.data$condition)
decoder.data$group <- paste(decoder.data$condition, decoder.data$source, sep="_")
decoder.data$group <- factor(decoder.data$group, levels = c("naive_BM", "infected_BM", "infected_lung"))
decoder.data$batch <- factor(decoder.data$batch)
row.names(decoder.data) = decoder.data$sample.ID
decoder.data <- decoder.data[order(decoder.data$group), ]
```

```{r counts}
counts <- read.table(file = "gene.counts.txt", header = TRUE, check.names=FALSE, row.names=1)
decoder.data <- decoder.data[decoder.data$sample.ID %in% colnames(counts),]
counts <- counts[,c(decoder.data$sample.ID)]

if (!identical(colnames(counts), decoder.data$sample.ID)) {
  stop("Column names in counts do not match sample IDs in decoder data")
}
```

# Samples

The following samples were part of this analysis:

```{r samples}
as_tibble(decoder.data[,c(-1)])
```

```{r}
color_palette <- c("pink", "#99c4ab", "#8898fa")
names(color_palette) <- levels(decoder.data$group)
```


```{r createDDS}
dds <- DESeq2::DESeqDataSetFromMatrix(countData = counts, 
                                      colData = decoder.data, 
                                      design = ~ batch + group)
dds <- estimateSizeFactors(dds)
vsd <- DESeq2::vst(dds, blind = TRUE)
normCounts = assay(vsd)
dds <- DESeq(dds)
baseMeanPerLvl <- sapply(levels(dds$group), function(lvl) rowMeans( counts(dds, normalized=TRUE)[,dds$group == lvl, drop=F]))
```


```{r read_in_deseq2_results}
de.all <- list()
alphaTR = 0.05
lfcThres = 0

file_list =  list.files("./differential_expression_res/", pattern = ".xlsx")
for (i in seq_along(file_list)) {
  file <- file_list[i]
  list_name <- gsub("deseq2_", "", file)
  list_name <- gsub(".padj0.05.res.xlsx", "", list_name)  
  de.all[[list_name]] <- read.xlsx(paste0("./differential_expression_res/", file), sheet = 1)
}

de.all.sig <- lapply(de.all, subset, padj < alphaTR & abs(log2FoldChange) > lfcThres)
```

# Heatmap of select genes

```{r heatmap, eval=T, fig.width=5, fig.height=5,results="asis", fig.align="center"}
genes <- c("Clec7a", "Clec4n", "Clec4d", "Clec4e", "Clec9a", "Cd69", "Cd209e", "Card9", 
           "Syk", "Tlr2", "Tlr7", "Tlr9", "Myd88", "Csf2ra", "Csf2rb", "Ifnar1", 
           "Ifnar2", "Ifna1", "Ifnb1", "Ifna2", "Ifna4", "Ifna5", "Ifna6", "Ifna9", 
           "Ifna11", "Ifna12", "Ifnl2", "Ifnl3", "Stat1", "Cxcl9", "Cxcl10", "Tnf", 
           "Il12b", "Icam1", "Hif1a")

annot_col = data.frame(group = decoder.data$group,row.names=decoder.data$sample.ID)

pheatmap(assay(vsd)[genes, ], 
               scale = "row", 
               show_rownames = TRUE, 
               show_colnames = FALSE,
               cluster_rows = FALSE, 
               cluster_cols = F, 
               main = "Heatmap of select genes", 
               fontsize_row = 10, 
               col = colorRampPalette(rev(brewer.pal(n = 7, name = "RdGy")))(100), 
               cellwidth = 10, 
               cellheight = 10, 
               treeheight_row = 0, 
               annotation_col = annot_col,
               annotation_colors =  list(group=color_palette[unique(as.character(decoder.data$group))]))
```


# Session Info
```{r session, message=FALSE, warning=FALSE, cache=TRUE,comment="",echo=FALSE, fig.width=10, fig.height=5.5, context="data"}
sessionInfo()
```

